version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        versions: ["18.x", "19.x"]
      - dependency-name: "react-native"
        versions: ["0.73.x", "0.74.x"]
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"