name: Dependency Updates
on:
  schedule:
    # Run weekly on Monday at 8 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Update dependencies
        run: |
          pnpm update --interactive false
          pnpm audit fix || true
      
      - name: Run tests
        run: pnpm test:ci
        continue-on-error: true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates performed by the weekly dependency update workflow.
            
            ### Changes
            - Updated npm dependencies to their latest compatible versions
            - Applied security fixes from npm audit
            
            ### Checklist
            - [ ] All tests pass
            - [ ] No breaking changes identified
            - [ ] Application builds successfully
            - [ ] Manual testing completed for critical paths
            
            Please review the changes and test thoroughly before merging.
          branch: deps/automated-update
          delete-branch: true
          labels: |
            dependencies
            automated