name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run tests
        run: pnpm test:ci
      
      - name: Build applications
        run: pnpm build
      
      - name: Build Docker images
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/xplore-api:${{ github.ref_name }} -f apps/api/Dockerfile.prod .
          docker build -t ghcr.io/${{ github.repository_owner }}/xplore-web:${{ github.ref_name }} -f apps/web/Dockerfile.prod .
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/xplore-api:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/xplore-web:${{ github.ref_name }}
          
          # Also tag as latest for production releases
          if [[ ! "${{ github.ref_name }}" =~ "-" ]]; then
            docker tag ghcr.io/${{ github.repository_owner }}/xplore-api:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/xplore-api:latest
            docker tag ghcr.io/${{ github.repository_owner }}/xplore-web:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/xplore-web:latest
            docker push ghcr.io/${{ github.repository_owner }}/xplore-api:latest
            docker push ghcr.io/${{ github.repository_owner }}/xplore-web:latest
          fi
      
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.changelog }}
            
            ## Docker Images
            - API: `ghcr.io/${{ github.repository_owner }}/xplore-api:${{ github.ref_name }}`
            - Web: `ghcr.io/${{ github.repository_owner }}/xplore-web:${{ github.ref_name }}`
            
            ## Deployment
            ```bash
            # Pull the latest images
            docker pull ghcr.io/${{ github.repository_owner }}/xplore-api:${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository_owner }}/xplore-web:${{ github.ref_name }}
            
            # Deploy using docker-compose
            export TAG=${{ github.ref_name }}
            docker-compose -f docker-compose.prod.yml up -d
            ```
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}